language: python

python:
  - "2.7"

cache:
  directories:
    - ${HOME}/.eggs-cache

virtualenv:
  system_site_packages: true

install:
  - ${TRAVIS_BUILD_DIR}/bootstrap.sh profiles/travis.cfg
  - ${TRAVIS_BUILD_DIR}/bin/buildout

before_script:
  - pip install -q flake8
  - export db_name=$(grep db_name ${TRAVIS_BUILD_DIR}/etc/openerp.cfg | cut -d ' ' -f 3)
  - export db_user=$(grep db_user ${TRAVIS_BUILD_DIR}/etc/openerp.cfg | cut -d ' ' -f 3)
  - export db_pass=$(grep db_password ${TRAVIS_BUILD_DIR}/etc/openerp.cfg | cut -d ' ' -f 3)
  - psql -c "CREATE USER ${db_user} WITH PASSWORD '${db_pass}' CREATEDB;" -U postgres

script:
  - flake8 ${TRAVIS_BUILD_DIR}/specific-parts/specific-addons --exclude=__init__.py
